FROM postgres:13

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    postgresql-server-dev-13

RUN git clone https://github.com/pgvector/pgvector.git

WORKDIR /pgvector

RUN make && make install


RUN apt-get clean && rm -rf /var/lib/apt/lists/*